project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://liveni-art.github.io/blog-math # you must change this appropriately for RSS feeds to work properly
  title: "Математический"
  favicon: images/favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/liveni-art/blog-math
      - icon: telegram
        href: https://t.me/mablob
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-title: "Содержание"



